onboot:
  - name: add-garden-ip-to-loopback
    image: alpine:3.6
    capabilities:
        - all
    net: host
    command: ["sh", "-c", "ifconfig lo:1 add 10.0.0.10 up"]

  - name: ensure-vcap-folder-exists
    image: alpine:3.6
    capabilities:
        - CAP_SYS_ADMIN
    binds:
      - /var/:/host_var:rbind,rshared
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir -p /host_var/lib/vcap && \
                           mount -v --bind /host_var/lib/vcap /host_var/lib/vcap && \
                           mount -v --make-shared /host_var/lib/vcap && \
                           ln -vs /var/lib/vcap /host_var/vcap"]

  - name: mount-bosh-deps
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "-label", "bosh-deps", "/var/vcap/director/cache"]

  - name: mount-cf-deps
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "-label", "cf-deps", "/var/vcap/cf/cache"]

services:
  - name: garden
    image: pivotal/garden-runc:dev
    rootfsPropagation: shared
    binds:
      - /var/lib:/var/lib
      - /var/vcap:/var/vcap:rshared,rbind
      - /etc/resolv.conf:/etc/resolv.conf

  - name: setup-bosh-lite-routing
    image: pivotal/bosh-lite-routing:dev
    net: host
    capabilities: ["all"]

  - name: expose-garden-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","127.0.0.1",
              "-host-port","7777",
              "-container-ip","127.0.0.1",
              "-container-port","7777"]

  - name: expose-bosh-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","127.0.0.1",
              "-host-port","25555",
              "-container-ip","10.245.0.2",
              "-container-port","25555"]

  - name: expose-router-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","127.0.0.1",
              "-host-port","35555",
              "-container-ip","10.244.0.34",
              "-container-port","80"]

# gaol create -n deploy-bosh -p \
#   --network 10.246.0.0/16 \
#   -r /var/vcap/director/cache/deploy-bosh.tar \
#   -m /var/vcap:/var/vcap \
#   -m /var/vcap/director/cache:/var/vcap/director/cache

# gaol create -n deploy-cf -p \
#   --network 10.246.0.0/16 \
#   -r /var/vcap/cf/cache/deploy-cf.tar \
#   -m /var/vcap:/var/vcap \
#   -m /var/vcap/cf/cache:/var/vcap/cf/cache

